<?php
/**
 * Created by PhpStorm.
 * User: luckeri20
 * Date: 20.09.2017
 * Time: 21:47
 */

namespace app\modules\parser\models;


class melbetaqp extends ParsingAbstractClass
{
    public $url;
    private $connections;
    /**
     * leonbets constructor
     */
    public function __construct() {
        parent::__construct(5);
        $this->connections = count($this->headers);
    }
    /**
     * leonbets destructor
     */
    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
    /**
     *
     */
    public function getLeages()
    {
        $url[] = [
            'href' => $this->base.'LiveFeed/Web_GetSports?lng=ru&champs=0&partner=8&cyberFlag=2'
        ];
        $channels = $this->proceedUrls($url);
        foreach ($channels as $key => $channel) {
            $html = curl_multi_getcontent($channel);
            /*echo '<pre>';
            print_r(curl_getinfo($channel));
            echo '</pre>';*/
            if ($html) {
                $json = json_decode(gzdecode($html));
                foreach ($json->Value[0]->Champs as $value) {
                    echo $value->LigaEng; echo '<br>';
                    $parsingUrl = "LiveFeed/Mobi_Get1x2?partner=8&count=20&lng=ru&sportId=0&cfview=0&champid={$value->LigaId}&cyberFlag=2";
                }
            }

        }
    }
}